// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// coconetA1
double coconetA1(Rcpp::NumericVector x, arma::mat A, arma::colvec y);
RcppExport SEXP _CoCoNet_coconetA1(SEXP xSEXP, SEXP ASEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(coconetA1(x, A, y));
    return rcpp_result_gen;
END_RCPP
}
// coconetA2
double coconetA2(Rcpp::NumericVector x, arma::mat A, arma::mat A2, arma::colvec y);
RcppExport SEXP _CoCoNet_coconetA2(SEXP xSEXP, SEXP ASEXP, SEXP A2SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(coconetA2(x, A, A2, y));
    return rcpp_result_gen;
END_RCPP
}
// coconetA3
double coconetA3(Rcpp::NumericVector x, arma::mat A, arma::mat A2, arma::mat A3, arma::colvec y);
RcppExport SEXP _CoCoNet_coconetA3(SEXP xSEXP, SEXP ASEXP, SEXP A2SEXP, SEXP A3SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A3(A3SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(coconetA3(x, A, A2, A3, y));
    return rcpp_result_gen;
END_RCPP
}
// coconetA4
double coconetA4(Rcpp::NumericVector x, arma::mat A, arma::mat A2, arma::mat A3, arma::mat A4, arma::colvec y);
RcppExport SEXP _CoCoNet_coconetA4(SEXP xSEXP, SEXP ASEXP, SEXP A2SEXP, SEXP A3SEXP, SEXP A4SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A3(A3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A4(A4SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(coconetA4(x, A, A2, A3, A4, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CoCoNet_coconetA1", (DL_FUNC) &_CoCoNet_coconetA1, 3},
    {"_CoCoNet_coconetA2", (DL_FUNC) &_CoCoNet_coconetA2, 4},
    {"_CoCoNet_coconetA3", (DL_FUNC) &_CoCoNet_coconetA3, 5},
    {"_CoCoNet_coconetA4", (DL_FUNC) &_CoCoNet_coconetA4, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoCoNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
