# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coconetA1 <- function(x, A, y) {
    .Call(`_CoCoNet_coconetA1`, x, A, y)
}

coconetA2 <- function(x, A, A2, y) {
    .Call(`_CoCoNet_coconetA2`, x, A, A2, y)
}

coconetA3 <- function(x, A, A2, A3, y) {
    .Call(`_CoCoNet_coconetA3`, x, A, A2, A3, y)
}

coconetA4 <- function(x, A, A2, A3, A4, y) {
    .Call(`_CoCoNet_coconetA4`, x, A, A2, A3, A4, y)
}

